### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by andrei-zgirvaci** [A-Tokyo/react-native-stripe-checkout-webview#48]
Hey, thanks for the awesome library!

I happen to experience some performance issues when opening the webview. Is it only me this is normal due to injecting HTML in the webview?

Thank you!

**Comment by A-Tokyo** [comment]
Hey @andrei-zgirvaci! I have not noticed "performance" issues per say, but there's definitely a minor delay since the HTML is injected as you mentioned.

There's no way around it atm, hopefully Stripe release an SDK for react-native so we don't need to use webview!

Please reopen the issue if you have further comments or questions!
